name: dhis_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - postgresql
  - psycopg2
  - jupyterlab
  - notebook
  - ipykernel
  - pip:
    - Django==5.0
    - djangorestframework==3.14.0
    - django-cors-headers==4.3.1
    - Pillow==10.1.0
    - python-dotenv==1.0.0
    - boto3==1.34.14
    - django-storages==1.14.2
    - gunicorn==21.2.0
    - whitenoise==6.6.0
    - portkey-ai==1.9.2
    - openai==1.35.0
    - dj-database-url==2.1.0
    - psycopg2-binary==2.9.9
    - redis==5.0.1
    - celery==5.3.4