# Generated by Django 5.0.2 on 2025-09-30 10:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_image', models.ImageField(upload_to='uploads/original/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('s3_url', models.URLField(blank=True, max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_diagnosis', models.DateField(blank=True, null=True)),
                ('case_detection_options', models.CharField(blank=True, max_length=50)),
                ('extracted_data', models.JSONField(blank=True, default=dict, null=True)),
                ('processed_data', models.JSONField(blank=True, default=dict)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
