# Generated by Django 5.0.2 on 2025-09-30 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='feature_type',
            field=models.CharField(choices=[('register', 'Patient Register Processing'), ('pdf', 'PDF Document Processing'), ('single_image', 'Single Image Processing')], default='single_image', max_length=20),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
